linters:
  Indentation:
    enabled: true
    character: space
    width: 4

  SelectorDepth:
    max_depth: 5

  PropertySortOrder:
    enabled: false

  Compass::PropertyWithMixin:
    enabled: true
